# Generated by Django 4.2.7 on 2023-11-30 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('image', models.ImageField(default='user/usuario_defecto.jpg', upload_to='users/', verbose_name='Imagen de perfil')),
                ('country', models.CharField(blank=True, max_length=40, null=True, verbose_name='Pais')),
                ('location', models.CharField(blank=True, max_length=40, null=True, verbose_name='Provincia')),
                ('celphone', models.CharField(blank=True, max_length=40, null=True, verbose_name='Celular')),
                ('instagram', models.CharField(blank=True, max_length=40, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=40, null=True, verbose_name='Facebook')),
                ('theraphys', models.CharField(blank=True, choices=[('reiki', 'Reiki'), ('memoria', 'Memoria Celular'), ('meditacion', 'Meditación'), ('Yoga', 'Yoga')], max_length=60, null=True, verbose_name='Terapias')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['id'],
            },
        ),
    ]
